return {
  git = '󰊢',
  dir = '',
  up_arrow = '',
  down_arrow = '',
  error = '',
  warn = '',
  hint = '',
  info = '',
  copilot_enabled = '',
  copilot_disabled = '',
  terminal = '',
  list = '',
  test = '',
}
